"""Create Quote and RandomQuoteChannel

Revision ID: 81158f0418f4
Revises: 
Create Date: 2023-12-22 23:21:21.726176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81158f0418f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(length=2048), nullable=False),
    sa.Column('author', sa.Text(length=256), nullable=False),
    sa.Column('submitted_by', sa.VARCHAR(length=32), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('approved', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('approved_by', sa.VARCHAR(length=32), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_id'), 'quotes', ['id'], unique=False)
    op.create_table('random_quote_channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('channel_id', sa.VARCHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_random_quote_channel_id'), 'random_quote_channel', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_random_quote_channel_id'), table_name='random_quote_channel')
    op.drop_table('random_quote_channel')
    op.drop_index(op.f('ix_quotes_id'), table_name='quotes')
    op.drop_table('quotes')
    # ### end Alembic commands ###
